Java 8 and Java 11 use different GC options

diff --git a/bin/uniffle b/bin/uniffle
--- a/bin/uniffle
+++ b/bin/uniffle
@@ -60,16 +60,28 @@ function uniffle_cmd_case
           -XX:InitiatingHeapOccupancyPercent=20 \
           -XX:G1HeapRegionSize=32m \
           -XX:+UnlockExperimentalVMOptions \
-          -XX:G1NewSizePercent=10 \
-          -XX:+PrintGC \
+          -XX:G1NewSizePercent=10"
+
+      JAVA8_GC_ARGS= " -XX:+PrintGC \
           -XX:+PrintAdaptiveSizePolicy \
           -XX:+PrintGCDateStamps \
           -XX:+PrintGCTimeStamps \
           -XX:+PrintGCDetails \
           -Xloggc:${RSS_LOG_DIR}/gc-%t.log"
 
-      JAVA11_EXTRA_ARGS=" -XX:+IgnoreUnrecognizedVMOptions \
+      JAVA11_GC_ARGS=" -XX:+IgnoreUnrecognizedVMOptions \
           -Xlog:gc*,gc+ergo*=trace:${RSS_LOG_DIR}/gc-%t.log:tags,time,uptime,level"
+
+      version=$(${JAVA} -version 2>&1 | awk -F '"' '/version/ {print $2}')
+      if [[ $version == "1.8"* ]]; then
+          GC_ARGS=$JAVA8_GC_ARGS
+      elif [[ $version == "11"* ]]; then
+          GC_ARGS=$JAVA11_GC_ARGS
+      else
+        echo "Exit with error: unknown java version ${version} ."
+        exit 1
+      fi
+
       UNIFFLE_OPTS="$UNIFFLE_OPTS $JVM_ARGS $JAVA11_EXTRA_ARGS"
 
       UNIFFLE_SUBCMD_SUPPORT_DAEMONIZATION="true"
@@ -85,17 +97,29 @@ function uniffle_cmd_case
           -XX:MaxGCPauseMillis=200 \
           -XX:ParallelGCThreads=20 \
           -XX:ConcGCThreads=5 \
-          -XX:InitiatingHeapOccupancyPercent=45 \
-          -XX:+PrintGC \
+          -XX:InitiatingHeapOccupancyPercent=45”
+
+      JAVA8_GC_ARGS= " -XX:+PrintGC \
           -XX:+PrintAdaptiveSizePolicy \
           -XX:+PrintGCDateStamps \
           -XX:+PrintGCTimeStamps \
           -XX:+PrintGCDetails \
           -Xloggc:${RSS_LOG_DIR}/gc-%t.log"
 
-      JAVA11_EXTRA_ARGS=" -XX:+IgnoreUnrecognizedVMOptions \
+      JAVA11_GC_ARGS=" -XX:+IgnoreUnrecognizedVMOptions \
           -Xlog:gc*,gc+ergo*=trace:${RSS_LOG_DIR}/gc-%t.log:tags,time,uptime,level"
-      UNIFFLE_OPTS="$UNIFFLE_OPTS $JVM_ARGS $JAVA11_EXTRA_ARGS"
+
+      version=$(${JAVA} -version 2>&1 | awk -F '"' '/version/ {print $2}')
+      if [[ $version == "1.8"* ]]; then
+          GC_ARGS=$JAVA8_GC_ARGS
+      elif [[ $version == "11"* ]]; then
+          GC_ARGS=$JAVA11_GC_ARGS
+      else
+        echo "Exit with error: unknown java version ${version} ."
+        exit 1
+      fi
+
+      UNIFFLE_OPTS="$UNIFFLE_OPTS $JVM_ARGS $GC_ARGS"
 
       UNIFFLE_SUBCMD_SUPPORT_DAEMONIZATION="true"
       RSS_CONF_FILE="${RSS_CONF_DIR}/coordinator.conf"
