Test uniffle reachable in docker cluster

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -63,7 +63,24 @@ jobs:
       run: ./deploy/docker/build.sh
       shell: bash
     - name: Start the docker cluster
-      run: docker compose -f deploy/docker/docker-compose.yml up --detach && sleep 10
+      run: |
+        for attempt in {1..3}
+        do
+          docker compose -f deploy/docker/docker-compose.yml up --detach
+          for i in {1..30}
+          do
+            sleep 1
+            if docker exec rss-spark-master-1 /usr/bin/getent hosts rss-coordinator-1 rss-coordinator-2 rss-shuffle-server-1 rss-shuffle-server-2 rss-shuffle-server-3
+            then
+              echo "docker cluster is up"
+              exit 0
+            fi
+          done
+          docker compose -f deploy/docker/docker-compose.yml down
+        done
+
+        echo "::error::Could not bring up Docker cluster"
+        exit 1
       shell: bash
     - name: Scale the docker cluster
       run: docker compose -f deploy/docker/docker-compose.yml scale shuffle-server=4 spark-worker=5
